# Import all libraries

In [1]:
RANDOM_STATE = 12345

#Manipulate data
import pandas as pd
import numpy as np

#Scale and split data
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix

#Classifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

#Ensembles
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

#Cross-Validation
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

#Easier to read
from pprint import pprint

#Draw ROC curve
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Breast_cancer.csv")

In [3]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df = df.rename(columns={'diagnosis':'outcome'})

In [5]:
df.head(5)

id outcome  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302       M        17.99         10.38          122.80     1001.0   
1    842517       M        20.57         17.77          132.90     1326.0   
2  84300903       M        19.69         21.25          130.00     1203.0   
3  84348301       M        11.42         20.38           77.58      386.1   
4  84358402       M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df["outcome"].replace({"M": 1, "B": 0}, inplace=True)
df["outcome"] = df["outcome"].astype(int)

In [7]:
df.head(5)

id  outcome  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302        1        17.99         10.38          122.80     1001.0   
1    842517        1        20.57         17.77          132.90     1326.0   
2  84300903        1        19.69         21.25          130.00     1203.0   
3  84348301        1        11.42         20.38           77.58      386.1   
4  84358402        1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [8]:
one = 0
zero = 0

for index, row in df.iterrows():
    if row['outcome'] == 1:
        one+=1
    else:
        zero+=1

print("Class balance:")
print("1",one)
print("0",zero)

Class balance:
1 212
0 357


In [9]:
df = df.drop('id', axis=1)
df = df.drop('Unnamed: 32', axis=1)

In [10]:
df.describe()

outcome  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  569.000000   569.000000    569.000000      569.000000   569.000000   
mean     0.372583    14.127292     19.289649       91.969033   654.889104   
std      0.483918     3.524049      4.301036       24.298981   351.914129   
min      0.000000     6.981000      9.710000       43.790000   143.500000   
25%      0.000000    11.700000     16.170000       75.170000   420.300000   
50%      0.000000    13.370000     18.840000       86.240000   551.100000   
75%      1.000000    15.780000     21.800000      104.100000   782.700000   
max      1.000000    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [11]:
(df==0).sum(axis=0)

outcome                    357
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean              13
concave points_mean         13
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                13
concave points_se           13
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst             13
concave points_worst        13
symmetry_worst               0
fractal_dimension_worst      0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   outcome                  569 non-null    int32  
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

# Seperate x and y and scale


In [13]:
x = df.drop('outcome', axis=1)
y = df['outcome']
scaler = StandardScaler()
X = scaler.fit_transform(x) 

# Classifiers

SVM

In [14]:
svmparam = SVC()

#Random values initial
X_svc_train, X_svc_test, y_svc_train, y_svc_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)
param_grid = {'C': [0.01,0.1,1,10,100], 'gamma': [10,1,0.1,0.01,0.001,0.0001],'kernel': ['sigmoid', 'poly', 'linear']}
grid_search = GridSearchCV(estimator = svmparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_svc_train, y_svc_train)
print( "Initial:", grid_search.best_params_)

#1st Round optimizing
param_grid = {'C': [8,9,10,11,12], 'gamma': [10,1,0.1,0.01,0.001,0.0001],'kernel': ['sigmoid', 'poly', 'linear']}
grid_search = GridSearchCV(estimator = svmparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_svc_train, y_svc_train)
print( "First round:", grid_search.best_params_)

#2nd Round optimizing
param_grid = {'C': [8,9,10,11,12], 'gamma': [0.008, 0.009, 0.01, 0.02, 0.03],'kernel': ['sigmoid', 'poly', 'linear']}
grid_search = GridSearchCV(estimator = svmparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_svc_train, y_svc_train)
print( "Second Round:", grid_search.best_params_)

#3rd Round optimizing
param_grid = {'C': [10,11,12,13,14], 'gamma': [0.008, 0.009, 0.01, 0.02, 0.03],'kernel': ['sigmoid', 'poly', 'linear']}
grid_search = GridSearchCV(estimator = svmparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_svc_train, y_svc_train)
print( "Third Round:", grid_search.best_params_)

#4th Round optimizing
param_grid = {'C': [10,11,12,13,14], 'gamma': [0.006, 0.007, 0.008, 0.009, 0.01],'kernel': ['sigmoid', 'poly', 'linear']}
grid_search = GridSearchCV(estimator = svmparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_svc_train, y_svc_train)
print( "Fourth Round:", grid_search.best_params_)

Initial: {'C': 10, 'gamma': 0.01, 'kernel': 'sigmoid'}
First round: {'C': 10, 'gamma': 0.01, 'kernel': 'sigmoid'}
Second Round: {'C': 12, 'gamma': 0.008, 'kernel': 'sigmoid'}
Third Round: {'C': 12, 'gamma': 0.008, 'kernel': 'sigmoid'}
Fourth Round: {'C': 12, 'gamma': 0.008, 'kernel': 'sigmoid'}


In [15]:
#Without hyperparametering
#svc = SVC(probability=True)

#Accuracy 0.9649122807017544
#Recall: 0.95
#Precision 0.95
#F1_Score: 0.9500000000000001
#AUC: 0.9926426426426426

#=== Confusion Matrix ===
#[[108   3]
# [  3  57]]

#With hyperparametering
svc = SVC(probability=True, C=12, gamma=0.008, kernel='sigmoid')

svc.fit(X_svc_train, y_svc_train)
y_svc_pred = svc.predict(X_svc_test)

svc_score = svc.predict_proba(X_svc_test)[: ,1]

recall_score_svc = recall_score(y_svc_test, y_svc_pred)
precision_score_svc = precision_score(y_svc_test, y_svc_pred)
f1_score_svc = f1_score(y_svc_test, y_svc_pred)

accuracy_score_svc = accuracy_score(y_svc_test, y_svc_pred)
recall_score_svc = recall_score(y_svc_test, y_svc_pred)
precision_score_svc = precision_score(y_svc_test, y_svc_pred)
f1_score_svc = f1_score(y_svc_test, y_svc_pred)
auc_svc = roc_auc_score(y_svc_test, svc_score)

print("Accuracy", accuracy_score_svc)
print("Recall:", recall_score_svc)
print("Precision", precision_score_svc)
print("F1_Score:", f1_score_svc)
print("AUC:", auc_svc)
print()

print("=== Confusion Matrix ===")
print(confusion_matrix(y_svc_test, y_svc_pred))

Accuracy 0.9766081871345029
Recall: 0.9333333333333333
Precision 1.0
F1_Score: 0.9655172413793104
AUC: 0.9912912912912912

=== Confusion Matrix ===
[[111   0]
 [  4  56]]


Decision Tree

In [16]:
dctparam = DecisionTreeClassifier(random_state = RANDOM_STATE)
X_dtc_train, X_dtc_test, y_dtc_train, y_dtc_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

#Random values initial
param_grid = {'max_depth': [None, 1,2,3,4], 'max_features': [None, 'auto', 'sqrt', 'log2'],
              'min_samples_leaf': [1,2,3,4,5], 'criterion' : ['gini', 'entropy'], 'min_samples_split' : [1,2,3,4,5]}
grid_search = GridSearchCV(estimator = dctparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_dtc_train, y_dtc_train)
print( "Initial:", grid_search.best_params_)

#First round
param_grid = {'max_depth': [2,3,4,5,6], 'max_features': [None, 'auto', 'sqrt', 'log2'],
              'min_samples_leaf': [1,2,3,4,5], 'criterion' : ['gini', 'entropy'], 'min_samples_split' : [1,2,3,4]}
grid_search = GridSearchCV(estimator = dctparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_dtc_train, y_dtc_train)
print( "First round:", grid_search.best_params_)

Initial: {'criterion': 'entropy', 'max_depth': 4, 'max_features': 'log2', 'min_samples_leaf': 3, 'min_samples_split': 2}
First round: {'criterion': 'entropy', 'max_depth': 4, 'max_features': 'log2', 'min_samples_leaf': 3, 'min_samples_split': 2}


In [17]:
#Without Hyperparametering

#dtc = DecisionTreeClassifier(random_state = RANDOM_STATE)

#Accuracy 0.8888888888888888
#Recall: 0.9166666666666666
#Precision 0.7971014492753623
#F1_Score: 0.8527131782945736
#AUC: 0.8952702702702702

#=== Confusion Matrix ===
#[[97 14]
# [ 5 55]]

#With Hyperparametering
dtc = DecisionTreeClassifier(random_state = RANDOM_STATE, max_depth=4, max_features='log2', criterion = 'entropy',
                             min_samples_leaf=3, min_samples_split=2)

dtc.fit(X_dtc_train,y_dtc_train)
y_dtc_pred = dtc.predict(X_dtc_test)

dtc_score = dtc.predict_proba(X_dtc_test)[: , 1]

accuracy_score_dtc = accuracy_score(y_dtc_test, y_dtc_pred)
recall_score_dtc = recall_score(y_dtc_test, y_dtc_pred)
precision_score_dtc = precision_score(y_dtc_test, y_dtc_pred)
f1_score_dtc = f1_score(y_dtc_test, y_dtc_pred)
auc_dtc = roc_auc_score(y_dtc_test, dtc_score)

print("Accuracy", accuracy_score_dtc)
print("Recall:", recall_score_dtc)
print("Precision", precision_score_dtc)
print("F1_Score:", f1_score_dtc)
print("AUC:", auc_dtc)
print()

print("=== Confusion Matrix ===")
print(confusion_matrix(y_dtc_test, y_dtc_pred))

Accuracy 0.935672514619883
Recall: 0.9166666666666666
Precision 0.9016393442622951
F1_Score: 0.9090909090909091
AUC: 0.9413663663663663

=== Confusion Matrix ===
[[105   6]
 [  5  55]]


Logistic Regression

In [18]:
lrparam = LogisticRegression()
X_lr_train, X_lr_test, y_lr_train, y_lr_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

#Random values initial
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [10, 1, 0.1, 0.001, 0.0001], 
              'max_iter' : [250, 500, 1000, 1250, 1500], 'solver' : ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Initial:", grid_search.best_params_)

#1st Round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [10, 1, 0.1, 0.001, 0.0001], 
              'max_iter' : [50,100,150,200,250], 'solver' : ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "First round:", grid_search.best_params_)

#2nd round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [0.5, 0.75, 1, 1.25, 1.5], 
              'max_iter' : [50,100,150,200,250], 'solver' : ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Second round:", grid_search.best_params_)

#3rd round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [0.5, 0.75, 1, 1.25, 1.5], 
              'max_iter' : [30,40,50], 'solver' : ['newton-cg']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Third round:", grid_search.best_params_)

#4th round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [0.5, 0.75, 1, 1.25, 1.5], 
              'max_iter' : [25,30,35], 'solver' : ['newton-cg']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Fourth round:", grid_search.best_params_)

#5th round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [0.5, 0.75, 1], 
              'max_iter' : [20,25,30], 'solver' : ['newton-cg']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Fifth round:", grid_search.best_params_)

#6th round
param_grid = {'penalty' : [None, 'l2','l1','elasticnet'], 'C' : [0.5, 0.75, 1], 
              'max_iter' : [15,20,25], 'solver' : ['newton-cg']}
grid_search = GridSearchCV(estimator = lrparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_lr_train, y_lr_train)
print( "Sixth round:", grid_search.best_params_)

Initial: {'C': 1, 'max_iter': 250, 'penalty': 'l2', 'solver': 'newton-cg'}
First round: {'C': 1, 'max_iter': 50, 'penalty': 'l2', 'solver': 'newton-cg'}
Second round: {'C': 0.75, 'max_iter': 50, 'penalty': 'l2', 'solver': 'newton-cg'}
Third round: {'C': 0.75, 'max_iter': 30, 'penalty': 'l2', 'solver': 'newton-cg'}
Fourth round: {'C': 0.75, 'max_iter': 25, 'penalty': 'l2', 'solver': 'newton-cg'}
Fifth round: {'C': 0.75, 'max_iter': 20, 'penalty': 'l2', 'solver': 'newton-cg'}
Sixth round: {'C': 0.75, 'max_iter': 15, 'penalty': 'l2', 'solver': 'newton-cg'}


In [19]:
#Without Hyperparametering
#lr = LogisticRegression()

#Accuracy 0.8021978021978022
#Recall: 0.7916666666666666
#Precision 0.8260869565217391
#F1_Score: 0.8085106382978724

#=== Confusion Matrix ===
#[[35  8]
# [10 38]]

#With Hyperparametering
#Trying a new level for C (0.5, which gave a better result than 0.75)
lr = LogisticRegression(C = 0.5, max_iter = 15, penalty = 'l2', solver = 'newton-cg')

lr.fit(X_lr_train,y_lr_train)
y_lr_pred = lr.predict(X_lr_test)

accuracy_score_lr = accuracy_score(y_lr_test, y_lr_pred)
recall_score_lr = recall_score(y_lr_test, y_lr_pred)
precision_score_lr = precision_score(y_lr_test, y_lr_pred)
f1_score_lr = f1_score(y_lr_test, y_lr_pred)

print("Accuracy", accuracy_score_lr)
print("Recall:", recall_score_lr)
print("Precision", precision_score_lr)
print("F1_Score:", f1_score_lr)
print()

print("=== Confusion Matrix ===")
print(confusion_matrix(y_lr_test, y_lr_pred))

Accuracy 0.9824561403508771
Recall: 0.95
Precision 1.0
F1_Score: 0.9743589743589743

=== Confusion Matrix ===
[[111   0]
 [  3  57]]


K-nearest neighbor

In [20]:
knnparam = KNeighborsClassifier()
X_knn_train, X_knn_test, y_knn_train, y_knn_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

#Random values initial
param_grid = {'n_neighbors': [2,3,4,5,6,7,8,9,10], 'weights': ['distance', 'uniform'],
              'algorithm': ['auto','ball_tree', 'kd_tree', 'brute']}
grid_search = GridSearchCV(estimator = knnparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_knn_train, y_knn_train)
print( "Initial:", grid_search.best_params_)

Initial: {'algorithm': 'auto', 'n_neighbors': 8, 'weights': 'distance'}


In [21]:
#Without Hyperparametering
#knn = KNeighborsClassifier()

#Accuracy 0.9649122807017544
#Recall: 0.9
#Precision 1.0
#F1_Score: 0.9473684210526316
#AUC: 0.9856606606606606

#=== Confusion Matrix ===
#[[111   0]
# [  6  54]]

#With Hyperparametering

knn = KNeighborsClassifier(n_neighbors = 8 , weights = 'distance', algorithm = 'auto')

knn.fit(X_knn_train,y_knn_train)
y_knn_pred = knn.predict(X_knn_test)

knn_score = knn.predict_proba(X_knn_test)[: , 1]

accuracy_score_knn = accuracy_score(y_knn_test, y_knn_pred)
recall_score_knn = recall_score(y_knn_test, y_knn_pred)
precision_score_knn = precision_score(y_knn_test, y_knn_pred)
f1_score_knn = f1_score(y_knn_test, y_knn_pred)
auc_knn = roc_auc_score(y_knn_test, knn_score)

print("Accuracy", accuracy_score_knn)
print("Recall:", recall_score_knn)
print("Precision", precision_score_knn)
print("F1_Score:", f1_score_knn)
print("AUC:", auc_knn)
print()

print("=== Confusion Matrix ===")
print(confusion_matrix(y_knn_test, y_knn_pred))

Accuracy 0.9590643274853801
Recall: 0.9
Precision 0.9818181818181818
F1_Score: 0.9391304347826087
AUC: 0.9863363363363363

=== Confusion Matrix ===
[[110   1]
 [  6  54]]


# Ensembles

Random Forest

In [22]:
#Optimizing parameters

rfparam = RandomForestClassifier(random_state=RANDOM_STATE)
X_rf_train, X_rf_test, y_rf_train, y_rf_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

#Random values initial
param_grid = {'max_depth': [1, 2, 3, 4], 'min_samples_leaf': [1,2,3,4], 
              'criterion' : ['gini', 'entropy'], 
              'min_samples_split' : [1,2,3,4], 'n_estimators' : [25, 50, 100, 150]}
grid_search = GridSearchCV(estimator = rfparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_rf_train, y_rf_train)
print( "Initial:", grid_search.best_params_)

#1st Round
param_grid = {'max_depth': [3,4,5], 'min_samples_leaf': [1,2], 
              'criterion' : ['gini', 'entropy'], 
              'min_samples_split' : [3,4,5], 'n_estimators' : [10,25,40]}
grid_search = GridSearchCV(estimator = rfparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_rf_train, y_rf_train)
print( "First round:", grid_search.best_params_)

Initial: {'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 25}
First round: {'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 25}


In [23]:
#Without Hyperparametering

rf = RandomForestClassifier(random_state=RANDOM_STATE)

#Accuracy 0.9473684210526315
#Recall: 0.95
#Precision 0.9047619047619048
#F1_Score: 0.9268292682926829
#AUC: 0.9765765765765764

#=== Confusion Matrix ===
#[[105   6]
# [  3  57]]

#With Hyperparametering
rf = RandomForestClassifier(n_estimators = 25, random_state=RANDOM_STATE, 
                           min_samples_leaf=1, min_samples_split=4, max_depth=4, criterion = 'gini')

rf.fit(X_rf_train, y_rf_train)
y_rf_pred = rf.predict(X_rf_test)

rf_score = rf.predict_proba(X_rf_test)[: , 1]

accuracy_score_rf = accuracy_score(y_rf_test, y_rf_pred)
recall_score_rf = recall_score(y_rf_test, y_rf_pred)
precision_score_rf = precision_score(y_rf_test, y_rf_pred)
f1_score_rf = f1_score(y_rf_test, y_rf_pred)
auc_rf = roc_auc_score(y_rf_test, rf_score)

print("Accuracy", accuracy_score_rf)
print("Recall:", recall_score_rf)
print("Precision", precision_score_rf)
print("F1_Score:", f1_score_rf)
print("AUC:", auc_rf)
print()

print("=== Confusion Matrix ===")
print(confusion_matrix(y_rf_test, y_rf_pred))

Accuracy 0.9473684210526315
Recall: 0.95
Precision 0.9047619047619048
F1_Score: 0.9268292682926829
AUC: 0.9813813813813813

=== Confusion Matrix ===
[[105   6]
 [  3  57]]


AdaBoost

In [24]:
abparam = AdaBoostClassifier(random_state=RANDOM_STATE)
X_ab_train, X_ab_test, y_ab_train, y_ab_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

#Random values initial
param_grid = {'n_estimators': [50, 100, 150, 200, 250], 'learning_rate': [1,0.1,0.01,0.001,0.0001]}
grid_search = GridSearchCV(estimator = abparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_ab_train, y_ab_train)
print( "Initial:", grid_search.best_params_)

#1st Round optimizing
param_grid = {'n_estimators': [150, 200, 250, 300, 350], 'learning_rate': [0.8,0.9,1,0,2.0,3.0]}
grid_search = GridSearchCV(estimator = abparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_ab_train, y_ab_train)
print( "First round:", grid_search.best_params_)

#2nd Round optimizing
param_grid = {'n_estimators': [350,400,450,500,550], 'learning_rate': [0.8,0.9,1,0,2.0,3.0]}
grid_search = GridSearchCV(estimator = abparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_ab_train, y_ab_train)
print( "Second round:", grid_search.best_params_)

#3rd Round optimizing
param_grid = {'n_estimators': [350,400,450,500,550], 'learning_rate': [0.5,0.6,0.7,0.8,0.9]}
grid_search = GridSearchCV(estimator = abparam, param_grid = param_grid, cv=3, n_jobs = -1)
grid_search.fit(X_ab_train, y_ab_train)
print( "Third round:", grid_search.best_params_)

Initial: {'learning_rate': 1, 'n_estimators': 250}
First round: {'learning_rate': 1, 'n_estimators': 350}
Second round: {'learning_rate': 0.8, 'n_estimators': 450}
Third round: {'learning_rate': 0.8, 'n_estimators': 450}


In [25]:
#Without Hyperparametering
#ab = AdaBoostClassifier(random_state=RANDOM_STATE)

#Accuracy 0.9590643274853801
#Recall: 0.9333333333333333
#Precision 0.9491525423728814
#F1_Score: 0.9411764705882353
#AUC: 0.9896396396396396

#=== Confusion Matrix ===
#[[108   3]
# [  4  56]]

#With Hyperparametering
ab = AdaBoostClassifier(n_estimators=450, learning_rate=0.8, random_state=RANDOM_STATE)

ab.fit(X_ab_train, y_ab_train)
y_ab_pred = ab.predict(X_ab_test)

ab_score = ab.predict_proba(X_ab_test)[: , 1]

accuracy_score_ab = accuracy_score(y_ab_test, y_ab_pred)
recall_score_ab = recall_score(y_ab_test, y_ab_pred)
precision_score_ab = precision_score(y_ab_test, y_ab_pred)
f1_score_ab = f1_score(y_ab_test, y_ab_pred)
auc_ab = roc_auc_score(y_ab_test, ab_score)

print("Accuracy", accuracy_score_ab)
print("Recall:", recall_score_ab)
print("Precision", precision_score_ab)
print("F1_Score:", f1_score_ab)
print("AUC:", auc_ab)
print()
print("=== Confusion Matrix ===")
print(confusion_matrix(y_ab_test, y_ab_pred))

Accuracy 0.9590643274853801
Recall: 0.95
Precision 0.9344262295081968
F1_Score: 0.9421487603305784
AUC: 0.98993993993994

=== Confusion Matrix ===
[[107   4]
 [  3  57]]
